### ISSUE TITLE
"null instance" errors occur when you try to access a node that doesn't exist. Usually this is down to misspelling. Since you didn't include the actual error message, I can't tell you where the problem is. Look at the error - it tells you exactly where the problem is.

### ISSUE THREAD

**Issue by KendallDoesCoding** [kidscancode/godot_tutorials#5]
"null instance" errors occur when you try to access a node that doesn't exist. Usually this is down to misspelling. Since you didn't include the actual error message, I can't tell you where the problem is. Look at the error - it tells you exactly where the problem is.

_Originally posted by @cbscribe in https://github.com/kidscancode/Godot3_dodge/issues/9#issuecomment-425289821_

I copied the code from GITHUB to my project and still got that error, the code is

extends RigidBody2D

const UP_IMPULSE: float = -55.0

func _input(event: InputEvent) -> void:
	if event is InputEventKey:
		if event.is_action_pressed("ui_select"):
			_penguin_jump()
			
func _penguin_jump() -> void:
	set_linear_velocity(Vector2(0, 0))
	apply_central_impulse(Vector2(0, UP_IMPULSE))
	$FlipAnimationPlayer.stop()
	$FlipAnimationSprite.play("Flap")

**Comment by cbscribe** [comment]
What line? What exact error? Your only `get_node()` appears to be `$FlipAnimationSprite`, so that is probably the thing that's wrong. Either your node is not actually named that, or it's not at that path (a child of the node this script is on).

**Comment by KendallDoesCoding** [comment]
Taking a break from Godot
